### ISSUE TITLE
Refactorisation issue

### ISSUE THREAD

**Issue by JusteRaimbault** [subdense/matching#13]
@julienperret in your last refactorisation, adding a preprocessing of connected components; it seems you did not push all your files - we are missing now a `matching.match(...)` function where the connected component code seems to have gone - I prefer not to touch anything so we don't have too much conflicts.
(cc @Mhdx20 )

**Comment by JusteRaimbault** [comment]
I did a temporary fix in this branch: https://github.com/subdense/matching/tree/temporary_fix - I prefer not to commit to main to avoid conflicts - @Mhdx20 you can use this branch to run the code while waiting for this issue to be fixed

**Comment by julienperret** [comment]
Sorry about that. I just pushed the fix.
