### ISSUE TITLE
QGIS issue 

### ISSUE THREAD

**Issue by mouhamadou-ndim** [subdense/matching#14]
I've an issue with qgis when i try to lunch it with my Linux system, here is the error:

`/usr/bin/qgis.bin: error while loading shared libraries: libpdal_util.so.13: cannot open shared object file: No such file or directory
`

**Comment by JusteRaimbault** [comment]
This is not related to this repository.
A fix seems to be given here though : https://github.com/qgis/QGIS/issues/52433

**Comment by Mhdx20** [comment]
Thanks @JusteRaimbault, QGIS works now!
