### ISSUE TITLE
Naming output file

### ISSUE THREAD

**Issue by JusteRaimbault** [subdense/matching#9]
To be closer to the naming policy, provide as a parameter the prefix for the output file, which will be named:
PREFIX_{EVOLUTION/LINKS}.gpkg

**Comment by julienperret** [comment]
Included as parameter "output_prefix" in commit 11c581d11eb808b99a528b2dd3bfd226bf56e158

**Comment by julienperret** [comment]
Included as parameter "output_prefix" in commit 11c581d11eb808b99a528b2dd3bfd226bf56e158
